### ISSUE TITLE
__get_current_locale doesn't fallback to DEFAULT

### ISSUE THREAD

**Issue by ktosiek** [django-money/django-money#203]
__get_current_locale uses hardcoded '' as a fallback locale instead of `moneyed.localization.DEFAULT`, which makes it render raw currency codes even when better defaults are available. I expected EUR to show up as € in any locale.

**Comment by Stranger6667** [comment]
Seems like not relevant, because ``CurrencyFormatter.format`` has it like default value for ``locale`` keyword argument:

https://github.com/limist/py-moneyed/blob/master/moneyed/localization.py#L56

The current implementation doesn't pass ``locale`` kwarg if ``__get_current_locale`` returned empty string:

```
return format_money(self, decimal_places=DECIMAL_PLACES)
```

https://github.com/django-money/django-money/blob/master/djmoney/models/fields.py#L144
