### ISSUE TITLE
Add tests for django migration framework

### ISSUE THREAD

**Issue by Stranger6667** [django-money/django-money#218]
Without tests it is not really possible to work on #139

**Comment by martarozek** [comment]
I also encountered a problem with migrations.
The situation was: there is a model, there are already some objects in the db, I add a `MoneyField` to it with `blank=True`, `null=True` and the `migrate` command crashes because NOT NULL constraint fails on the currency field. Adding a default currency didn't help.
My assumption is that when adding a nullable money field, the currency field doesn't inherit the nullability.

**Comment by Stranger6667** [comment]
Hi, @martarozek !
Could you, please, specify what Python/Django/django-money version you're running?

**Comment by martarozek** [comment]
Python3.5
Django==1.10
django-money==0.9.1

**Comment by martarozek** [comment]
I found this snippet:
```
    def add_currency_field(self, cls, name):
        """
        Adds CurrencyField instance to a model class.
        """
        currency_field = CurrencyField(
            max_length=3, price_field=self,
            default=self.default_currency, editable=False,
            choices=self.currency_choices
        )
```
Maybe this is the place where `null=self.nullable` is missing?

**Comment by Stranger6667** [comment]
Since the tests are merged into the main branch I close this issue.
