### ISSUE TITLE
Better changelog

### ISSUE THREAD

**Issue by Stranger6667** [django-money/django-money#302]
Something like http://keepachangelog.com/en/0.3.0/

**Comment by drdaeman** [comment]
While only tangentially related - maybe it would be a good idea to adopt [semver](http://semver.org/) or some conceptually-similar policy?

just that it was a little frustrating when patch-level release (0.11.1) broke compatibility.

**Comment by Stranger6667** [comment]
I absolutely agree, that we should use semver. The issue with the release was done by accident and I'm sorry about that. Initial plan was to make a bug fix release without these dropping support changes and the 0.11.x branch was planned to be the legacy branch for bugfixes only and 0.12 release should be the first release without support for python 2.6, django <1.8 etc. 
In fact we still can fix this by reverting some things, making new minor release, and reapplying these changes against the master branch.
@benjaoming , what do you think?

**Comment by benjaoming** [comment]
@drdaeman that wasn't intended, certainly we can be more explicit about semver.

As I mentioned earlier, it's fine to have the 0.11.x branch, we just had some issues of bug fixes for 0.11 going to master, but the two branches are now identical.

Since the 0.11.x branch is still there, let's use it as a release branch and have master be our 0.12 development branch.

**Comment by Stranger6667** [comment]
The issue is solved.
