### ISSUE TITLE
That thing that everybody talks about

### ISSUE THREAD

**Issue by benjaoming** [django-money/django-money#422]
@Stranger6667 from a perception that GitLab seems to have more features and everybody else is doing it: Shall we make the move?

(I don't personally like Microsoft, but we can also make the decision without this aspect, just wanted to disclose)

**Comment by simonmcconnell** [comment]
What are the benefits?

**Comment by ZuluPro** [comment]
@benjaoming 
We should go to gitlab now, archive this repo as mirror.

@simonmcconnell 
Avoid to work directly for Microsoft benefits.

**Comment by benjaoming** [comment]
@simonmcconnell

GitLab has more features, but it will likely be an impossible choice between UI simplicity and features. At DjangoCon a month ago, I heard positive feedback from a couple of using GitLab. One of them said it was "fast", which used to be my main argument against it. And yes, I would agree, Navigating GitLab has performed as fast as Github lately.

**Comment by ZuluPro** [comment]
@humrochagf We don't follow the herd, we lead it.
In facts, the first link to the code is pypi which links to GitHub.
As most people don't contribute at all, bet on GitHub's community is not relevant.

**Comment by simonmcconnell** [comment]
The issue was opened with the reason "everybody is doing it", which is herd mentality. The supporting arguments are an emotional reaction to the Microsoft acquisition and unexplained extra features.  Requests should provide sufficient detail for consideration.

**Comment by ZuluPro** [comment]
@simonmcconnell My factor is not linked to emotions or features:
- Open-source should play on resilience. GitHub have ever been a growing SPOF. And for many free internet services, I prone degooglelisation. The fact that Microsoft bought it, has just centerize more the thing.
- About features, yeah GitLab has really really more features than GitHub. The simple fact that it is open-source makes it more useful with more features each month

**Comment by Stranger6667** [comment]
From the functional point of view, Gitlab is really good. I use it at work and the most notable difference for me is a built-in CI, otherwise, the relevant for me features are more or less the same. Is there any killer features that exist in Gitlab, but don't exist in Github?
I mean relevant, useful features in the **free** version, features that will improve my developer experience.

Moving to Gitlab, only because Github's ownership change doesn't make sense for me. For me, it doesn't matter working for Microsoft benefits or working for Gitlab Inc. benefits.

If Gitlab is significantly better than Github, in terms of usability and comfort for development, then we should consider a move, otherwise, I'd stick with Github.

> We should go to gitlab now, archive this repo as mirror.

Currently, it is only a few days since the decision was published and **nothing** was changed. I'd like to know what is the exact roadmap for changes in Github from MS side, before taking any decisions about moving / archiving. If something will change in some bad way, then we should consider changing the platform.

BTW. Am I missing something about MS? From my pov they didn't screw up LinkedIn, are there any recent MS acquisitions when they did screw up a product they bought?

**Comment by benjaoming** [comment]
@Stranger6667 

I haven't had enough experience with GitLab to analyze pros/cons. But there are some interesting prospects about CI.

https://usersnap.com/blog/gitlab-github/

I do find it extremely appealing that GitLab is an open source platform.

> Moving to Gitlab, only because Github's ownership change doesn't make sense for me. For me, it doesn't matter working for Microsoft benefits or working for Gitlab Inc. benefits.

That might be a good point. Just remember that Microsoft didn't build GitHub. Actually they haven't really built anything that use.. only acquired it. Github was used to listen to its users and make sensible changes, improving the platform significantly over the years.

To me, it doesn't necessarily mean that this development will stop, but only more likely. Besides, there are some other threats to be vary of...

> when they did screw up a product they bought?

Skype was already screwed up by eBay whom didn't develop it much, but MS didn't really fix anything and only made account registration a mess.

They completely lost Hotmail after buying that and Google took over with Gmail. Other things that people recall are Nokia. LinkedIn certainly wasn't fixed by Microsoft, neither, but yeah it was a mess before.

MS started merging the user accounts on Skype in some untransparent way with other MS services, I guess they might want to force GitHub users to do the same. I think another similar threat might be to merge LinkedIn data with GitHub performance data and take total control of the software developer hiring market.

**Comment by Stranger6667** [comment]
Closing it for now - seems like nothing significantly changed for `django-money` during the last ~11 months. 

Feel free to reopen if there are any points we need to reconsider

**Comment by benjaoming** [comment]
Anyone that might recommend an updated comparison of Github vs Gitlab in terms of features/UI/speed etc?
