### ISSUE TITLE
Use black for code formatting

### ISSUE THREAD

**Issue by Stranger6667** [django-money/django-money#481]
@benjaoming 

Hej Ben! What do you think? it will cut a lot of discussions about code formatting and make it consistent

**Comment by benjaoming** [comment]
Hi @Stranger6667 :)

Great to meet you IRL!!

I think Black is a nice project, which solves some of the few short-comings of flake8 and isort. But I wish they would file a PEP instead of privatizing coding standards.

Please feel free to investigate if its a feasible replacement for the current tools, I'm not opinionated, least of all to have a discussion about having a discussion about code style :smile:

**Comment by Stranger6667** [comment]
Hi @benjaoming 

Likewise :) It was great, indeed!

I believe it could be an addition rather than replacement, will check how it could look like soon :)

> I'm not opinionated, least of all to have a discussion about having a discussion about code style 

:smile:
