### ISSUE TITLE
Relase 0.15 is missing in changelog on RTD

### ISSUE THREAD

**Issue by washeck** [django-money/django-money#504]
See https://django-money.readthedocs.io/en/latest/changes.html , 0.15 is not listed there.

**Comment by benjaoming** [comment]
Thanks @washeck, that's a nice find! I think there must be some kind of build error holding back new builds.

**Comment by benjaoming** [comment]
At least, 0.15 was already mentioned in `master`.

**Comment by browniebroke** [comment]
I've had the same problem on other projects of mine and it's most likely due to a deprecations in the RTD webhook: https://blog.readthedocs.com/webhook-deprecations/

If you look at the build section, there haven't been a build in 7 months: https://readthedocs.org/projects/django-money/builds/


The fix is simple but needs to be carried out by an admin of the project. Here are the steps:

1. Go in the RTD admin panel for integrations: https://readthedocs.org/dashboard/django-money/integrations/
2. Get the GitHub incoming webhook, either by clicking in the existing enmtry or by adding a new one
3. Copy the given URL into the webhook section on Github https://github.com/django-money/django-money/settings/hooks

**Comment by Stranger6667** [comment]
Hej :) added you to RTD curators list :)

Will take a look at the issue soon

**Comment by benjaoming** [comment]
I went ahead and followed @browniebroke 's steps. And it works! Thanks!
