### ISSUE TITLE
Why is ROUND_HALF_EVEN the default everywhere?

### ISSUE THREAD

**Issue by denizdogan** [django-money/django-money#520]
Why is `ROUND_HALF_EVEN` used across all the formatting definitions? It would seem to me like `decimal.ROUND_HALF_UP` is the proper one to use?

```
In [40]: Decimal("2953.125").quantize(Decimal("1.00"), decimal.ROUND_HALF_EVEN)
Out[40]: Decimal('2953.12')

In [41]: Decimal("2953.125").quantize(Decimal("1.00"), decimal.ROUND_HALF_UP)
Out[41]: Decimal('2953.13')
```

I'm from Sweden. Here it should definitely be 2953.15, but it's probably different for other currencies?

**Comment by Stranger6667** [comment]
Hello @denizdogan !
Django-money uses the formatting from `py-moneyed` project and we add only `decimal_places` here - https://github.com/django-money/django-money/blob/master/djmoney/money.py#L64
Otherwise, the formatting configuration is taken from `py-moneyed`

 It might be more appropriate to raise this question there - https://github.com/limist/py-moneyed

**Comment by denizdogan** [comment]
@Stranger6667 You're right, will ask there!
