### ISSUE TITLE
Support most recent changes in py-moneyed for formatting

### ISSUE THREAD

**Issue by spookylukey** [django-money/django-money#567]
In [py-moneyed](https://github.com/limist/py-moneyed) we have just merged a change that deprecates `moneyed.localization` in favour of `moneyed.l10n`. The latter contains a single, new `format_money` function, which simply delegates to [Babel number formatting functions](https://babel.pocoo.org/en/latest/api/numbers.html). This fixes many long-standing issues in our formatting, and frees us of the need to try to manually define all the different formats - we get them from Babel, which is based on [CLDR](http://cldr.unicode.org/) data.

Before releasing a new version of `py-moneyed`, I'd like to check that the new API works for django-money, since I know it is a major user of py-moneyed. Would it be possible for you to do an experimental branch that doesn't use `moneyed.localization` at all (or at least, only as a fallback)?

Please see the [new docs](https://py-moneyed.readthedocs.io/en/latest/formatting.html) and [CHANGES.rst](https://github.com/limist/py-moneyed/blob/master/CHANGES.rst)

Thanks.

**Comment by Stranger6667** [comment]
I was hoping for this for years :) Finally, it is happening. I think that it is a great change and I'd be happy to have it in `django-money`. What do you think, @benjaoming ?

**Comment by spookylukey** [comment]
FYI - I have released py-moneyed 1.0 now, without waiting for a reply here, as people have been waiting a few months. I don't think you should have too much problem integrating the changes.

**Comment by antonagestam** [comment]
Hi! I started looking into this as it seems like the best issue to work on to try to get django-money on par with py-moneyed. I almost immediately bumped into an issue that I haven't managed to figure out on my own.

In the [current implementation](https://github.com/django-money/django-money/blob/78e7aed33ba2601eacf320a2f766fec4e3e14249/djmoney/money.py#L100) of django-money's `Money.__str__()`, the call to `format_money()` includes a `decimal_places` kwarg that is set to `Money.decimal_places_display` which can either be read from settings or set directly on a `Money` instance.

However, in [the new](https://github.com/py-moneyed/py-moneyed/blob/master/moneyed/l10n.py#L10) babel-backed `format_money()` implementation there is no `decimal_places` argument. Babel does allow overriding the number of decimal places displayed, but it seems like it is only possible by overriding the format (and setting `currency_digits=False`). So it's a little unclear to me if the current behavior of allowing overriding the number of decimal places (without providing a formatting string) can be easily supported.

It might be possible by finding out what formatting string babel is going to use and altering that string, but that seems like a pretty bad option because: a) it would probably require accessing private stuff in babel (don't even know if that's possible), and b) altering the format string seems very error-prone and unpredictable.

Another alternative, which seems much more plausible to me is to discontinue support for `decimal_places_display`, possibly providing support for overriding `format` and `currency_digits` instead. This could be done in such a way that `decimal_places_display` is deprecated in the next major version and removed in the next one after that, and living side by side with the new babel-backed formatting while deprecated.

So, in version 2.0 this would happen:

- We introduce a setting `ENABLE_BABEL_FORMATTING` that defaults to `False`.
- Setting and reading `decimal_places_display` starts giving a deprecation warning.
- Setting `CURRENCY_DECIMAL_PLACES_DISPLAY` in settings starts giving a deprecation warning.
- Setting `ENABLE_BABEL_FORMATTING = True` and `decimal_places_display` returning anything other than None starts giving an error as this would be ambiguous.
- Setting `ENABLE_BABEL_FORMATTING = True` makes `Money.__str__` call the new `l10n.format_money()`.
- Settings and properties for `format` and `currency_digits` are introduced, similar to how `decimal_places_display` currently works.

What do you think? Can you come up with some feasible way to keep supporting `decimal_places_display` that I am missing, or does the proposed deprecation plan sound like a good idea?

**Comment by Stranger6667** [comment]
Hi @antonagestam 

Thank you for stepping on this :) I appreciate it :)

Generally, `django-money` always tried to follow the behavior of `pymoneyed` and provide a proxy to its formatting features. Those features changed and so I guess that `django-money` should follow these changes. I sympathize the option B on that matter.

I like the plan and timing :) The only thing that worries me is `ENABLE_BABEL_FORMATTING` - it will be nice to avoid introducing a temporary config option, but it seems like a fair trade-off to have a configurable and smooth upgrade.

**Comment by antonagestam** [comment]
@Stranger6667 

> I like the plan and timing :) The only thing that worries me is ENABLE_BABEL_FORMATTING - it will be nice to avoid introducing a temporary config option, but it seems like a fair trade-off to have a configurable and smooth upgrade.

I agree, it would be nice if that can be avoided. Perhaps it should just be inferred by `CURRENCY_DECIMAL_PLACES_DISPLAY` and `decimal_places_display` both being unset? That makes sense to me for the moment, but would have to look a bit closer again ;)

**Comment by Stranger6667** [comment]
> Perhaps it should just be inferred by CURRENCY_DECIMAL_PLACES_DISPLAY and decimal_places_display both being unset?

Interesting idea! Seems good to me :) If the user sets them then the behavior will be the same + a warning is emitted. Then `3.0` is released, those settings are discontinued and `babel` is used by default. The only thing is that if those options are not set, then they behavior will change, however, I think it should be ok for a breaking change - there is a way to set it back

**Comment by antonagestam** [comment]
@Stranger6667 Cool! I'll look into the details and amend the plan as soon as I find the time. :)

**Comment by antonagestam** [comment]
Alright, got a bit of time now. Here's the amended plan that I'll start working on:

In version 2.0:

- The py-moneyed dependency is pinned to `>1,<2`.
- Setting and reading `decimal_places_display` starts giving a deprecation warning.
- Setting `CURRENCY_DECIMAL_PLACES_DISPLAY` in settings starts giving a
  deprecation warning.
- Not setting `CURRENCY_DECIMAL_PLACES_DISPLAY`, and not setting
  `Money.decimal_places_display` results in `Money.__str__` using the new
  `l10n.format_money()`.
- Settings and properties for `format` and `currency_digits` are introduced,
  similar to how `decimal_places_display` currently works.

In version 3.0:

- The py-moneyed dependency is pinned to `>2`.
- Calling the old `localization.format_money()` is removed, we are now always
  calling the new `l10n.format_money()`.
- The `decimal_places_display` property is removed.
- The `CURRENCY_DECIMAL_PLACES_DISPLAY` setting is removed.

**Comment by Stranger6667** [comment]
Looks great to me :)

**Comment by Stranger6667** [comment]
Released in `2.0`
