### ISSUE TITLE
'latest' docs not up to date

### ISSUE THREAD

**Issue by adamchainz** [django-money/django-money#660]
https://django-money.readthedocs.io/en/latest/changes.html does not show the 2.1.1 docs - I think you probably need to update Read the Docs for the `master` -> `main` change.

The "stable" version, which uses tags, shows the new version - but the docs links point to "latest" so most users probably won't see this.

**Comment by benjaoming** [comment]
Thanks for noticing, Adam! It's been fixed now :+1:

**Comment by benjaoming** [comment]
(the issue was something like this: RTD was set to use the VCS default branch, which indeed is `main`.. but somehow it hadn't discovered that it should build `latest` again or maybe doesn't see when the default VCS branch changes.. so it wasn't until I forced the default branch setting on RTD to `main` and did another build that it got updated)

**Comment by adamchainz** [comment]
Brilliant. 😎
