### ISSUE TITLE
PyPI package is possibly outdated

### ISSUE THREAD

**Issue by Shanto** [django-money/django-money#68]
> Django’s from `SelectField` excepts a list of touples, it got passed a
list of `Currencies`. This should now allow to use from `MoneyField` on
it’s own. (quoted from commit https://github.com/jakewins/django-money/commit/8aeca9ea10a27ec1784d5faaba3e4c93a0c597c1)

\- https://github.com/jakewins/django-money/commit/8aeca9ea10a27ec1784d5faaba3e4c93a0c597c1#diff-ed331326234013b6a23d2f062bf9d1eaL11
\+ https://github.com/jakewins/django-money/commit/8aeca9ea10a27ec1784d5faaba3e4c93a0c597c1#diff-ed331326234013b6a23d2f062bf9d1eaR14

This fix is not present in the PyPI release (https://pypi.python.org/pypi/django-money).

**Comment by oppianmatt** [comment]
no versions numbers listed. Is this issue even still valid? What should be on pypi should be stated.

**Comment by benjaoming** [comment]
Garh, so apparently version is hardcoded in setup.py. For future releases, we should put the version number in django-money and import it to setup.py but we can't do that currently because `__init__.py` imports loads of dependencies that can make setup.py fail to run :/

For future releases, we also miss tags on commits.
